#!/bin/sh
#
# CVL build system to check or configure building process after installation.
#

SOURCE_DIR=$1
BUILD_DIR=$2
INSTALL_DIR=$3

if [ -d ${INSTALL_DIR}/icons/EmapIcons ]; then
    rm -rf ${INSTALL_DIR}/icons/EmapIcons
fi

cp -r ${SOURCE_DIR}/EmapIcons ${INSTALL_DIR}/icons

# Copy module validation script to package directory.
if [ ! -f ${INSTALL_DIR}/validate_module.sh ]; then
    cp ${SOURCE_DIR}/validate_module.sh ${INSTALL_DIR}
fi
